hostA:
  IP: 198.32.43.16
  interfaceName: 'ens2f0.43'
hostB:
  IP: 198.32.43.16
  interfaceName: 'ens2f0.43'
# How long to scrape host-level data (in seconds)
scrapeDuration: 900
# Scrape interval duration (in seconds)
scrapeInterval: 30
# Collect all packets continuously over the scrape interval
# Not recommended for general use cases, but provides additional information if set to True
# Defaults to False, collects the most recent burst (1 second's worth of data) at the current scrape interval
continuousCollect: False
# TCP Metric Port
tcpPort: 9191
# Receiving end IP Address, where pushgateway located
receiverIP: 'localhost' #change it
