# Number of switches
switchNum: 1
dashTitle: "Bottom Flow Dashboard"
# Host 1 Specifics 
hostA:
  IP: 198.32.43.16
  interfaceName: 'ens2d1.1001'
  interfaceIP: '10.10.101.1/24'
  vlan: 1001
  nodeExporterPort: 9100
  switchPort: 
    ifName: 'TenGigabitEthernet 0/43'
    ifIndex: 1054084
# Host 2 Specifics
hostB:
  IP: 198.32.43.15
  interfaceName: 'ens2d1.1001'
  interfaceIP: '10.10.101.2/24'
  vlan: 1001
  nodeExporterPort: 9100
  switchPort: 
    ifName: 'TenGigabitEthernet 0/42'
    ifIndex: 1053956
# Prometheus source specifics
switchData:
  job_name: 'snmp1'
  scrapeInterval: 15s
  scrapeDuration: 5h
  target: 172.16.1.14
  # if-mib and F10-IF-EXTENSION-MIB
  params: [1.3.6.1.2.1.31, 1.3.6.1.4.1.6027.3.11]
