version: '3.8'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - monitor-net
    deploy:
      mode: global
      restart_policy:
          condition: on-failure
          
  # node-exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   restart: unless-stopped
  #   volumes:
  #     - /:/host:ro,rslave
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   expose:
  #     - 9100
    
  # snmp-exporter:
  #   image: prom/snmp-exporter:latest
  #   container_name: snmp-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - ./SNMPExporter/snmp.yml:/etc/snmp_exporter/snmp.yml
  #   expose:
  #     - 9116
  #   command: 
  #     - '--config.file=/etc/snmp_exporter/snmp.yml'

              # subprocess.run("sudo docker run -d --name snmp-exporter -p 9116:9116     -v $PWD/snmp.yml:/etc/snmp_exporter/snmp.yml p")