# Number of switches
switchNum: 4
# Grafana Dashboard Title
dashTitle: "SLAC-ESnet-NERSC Dashboard"
# Prometheus Port
prometheusPort: 9090
# Host 1 Specifics (SLAC DTN End System)
hostA:
  IP: '134.79.103.64/24'
  interfaceName:
  interfaceIP: 
  nodeName: 'psexport-servers'
  vlan: 
  nodeExporterPort: 9100
# Host 2 Specifics (NERSC DTN End System)
hostB:
  IP:
  interfaceName: 
  interfaceIP: 
  nodeName: 
  vlan: 
  nodeExporterPort: 9100
# Switch 1 Specifics (SLAC) (rtr-border1-7k)
switchDataA:
  name: 'rtr-border1-7k'
  job_name: 'snmp1'
  target: '192.188.37.130'
  portIn: 
    ifName: 
    ifIndex: 
  portOut: 
    ifName: 
    ifIndex: 
# Switch 2 Specifics (ESnet) (slac50n-cr6)
switchDataB: 
  name: 'slac50n-cr6'
  job_name: 'snmp2'
  target:
  portIn: 
    ifName: 
    ifIndex: 
  portOut: 
    ifName: 
    ifIndex: 
# Switch 3 Specifics (ESnet) (lbnl50-cr6)
switchDataC: 
  name: 'lbnl50-cr6'
  job_name: 'snmp3'
  target:
  portIn: 
    ifName: 
    ifIndex: 
  portOut: 
    ifName: 
    ifIndex: 
# Switch 4 Specifics (NERSC) (BR2)
switchDataD: 
  name: 'BR2'
  job_name: 'snmp4'
  target: '192.188.37.132'
  portIn: 
    ifName: 
    ifIndex: 
  portOut: 
    ifName: 
    ifIndex: 
