switchData:
  job_name: 'snmp1'
  scrapeInterval: 15s
  scrapeDuration: 5h
  timeOutDuration: 5s
  target: 192.188.37.132
  # if-mib
  params: [1.3.6.1.2.1.31]
  # Community Read string
  communityString: 'test'
  portIn: 
    ifName: 
    ifIndex: 
  portOut: 
    ifName: 
    ifIndex: 
  snmpGeneratorPath: '/root/go/src/github.com/prometheus/snmp_exporter/generator'
  snmpExporterPath: '/usr/local/bin/snmp_exporter'
  dynamicDashboardPath: '/root/DynamicDashboard'
