version: '3.8'

networks:
  site-net:

services:

  arp-exporter:
    image: arp_exporter
    network_mode: "host"
    restart: always
    volumes:
      - ../config.yml:/etc/arp_exporter/arp.yml
      - ../Metrics/ARPMetrics/jsonFiles:/etc/arp_exporter/jsonFiles
    ports:
      - 9192:9192
    deploy:
      restart_policy:
        condition: on-failure
