version: '3.8'

networks:
  site-net:

services:

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - site-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  
  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ./SNMPExporter/src/github.com/prometheus/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    command: 
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    ports:
      - 9116:9116
    networks:
      - site-net
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
