version: '3.8'

services:

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - site-net
    deploy:
      mode: global

  # snmp-exporter:
  #   image: prom/snmp-exporter
  #   volumes:
  #     - ../SNMPExporter/src/github.com/prometheus/generator/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
  #   command: 
  #     - '--config.file=/etc/snmp_exporter/snmp.yml'
  #   ports:
  #     - 9116:9116
  #   networks:
  #     - site-net
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #     placement:
  #       constraints:
  #         - node.role == worker

  arp-exporter:
    image: arp_exporter
    network_mode: "host"
    restart: always
    volumes:
      - ../config.yml:/etc/arp_exporter/arp.yml
    ports:
      - 9191:9191
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  
  # tcp-exporter:
  #   image: tcp_exporter
  #   network_mode: "host"
  #   restart: always
  #   volumes:
  #     - ../config.yml:/etc/tcp_exporter/tcp.yml
  #   ports:
  #     - 9192:9192
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #     placement:
  #       constraints:
  #         - node.role == worker

