version: '3.8'

networks:
  my-network:
    driver: bridge

services:

  node-exporter:
    hostname: "host1"
    image: quay.io/prometheus/node-exporter:latest
    # network_mode: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - target: 9100
      - published: 9100
      - mode: host
    restart: always
    deploy:
      mode: global
      endpoint_mode: dnsrr

      
  # snmp-exporter:
  #   image: prom/snmp-exporter:latest
  #   container_name: snmp-exporter
  #   network_mode: "host"
  #   volumes:
  #     - ../SNMPExporter/src/github.com/prometheus/generator/snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
  #   command: 
  #     - '--config.file=/etc/snmp_exporter/snmp.yml'
  #   ports:
  #     - 9116:9116
  #   restart: always

  # arp-exporter:
  #   build: 
  #     context: ../Metrics
  #     dockerfile: arp.Dockerfile
  #   container_name: arp-exporter
  #   network_mode: "host"
  #   restart: always
  #   volumes:
  #     - ../config.yml:/etc/arp_exporter/arp.yml
  #   ports:
  #     - 9191:9191

  # tcp-exporter:
  #   build: 
  #     context: ../Metrics
  #     dockerfile: tcp.Dockerfile
  #   container_name: tcp-exporter
  #   network_mode: "host"
  #   restart: always
  #   volumes:
  #     - ../config.yml:/etc/tcp_exporter/tcp.yml
  #   ports:
  #     - 9192:9192
