version: '3.8'

services:

  node-exporter:
    hostname: "host1"
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
    
      
  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ../SNMPExporter/src/github.com/prometheus/snmp_exporter/generator/snmp.yml:/etc/snmp_exporter/snmp.yml
    network_mode: "host"
    ports:
      - 9116:9116
  

  # arp-exporter:
  #   build: 
  #     context: ../Metrics
  #     dockerfile: arp.Dockerfile
  #   container_name: arp-exporter
  #   network_mode: "host"
  #   restart: always
  #   volumes:
  #     - ../config.yml:/etc/arp_exporter/arp.yml
  #     - ../Metrics/ARPMetrics/jsonFiles:/jsonFiles
  #     - ../Metrics/ARPMetrics/arpFiles:/arpFiles
  #     - ../Metrics/ARPMetrics/pingStat:/pingStat
  #   ports:
  #     - 9192:9192
  #   deploy:
  #     restart_policy:
  #       condition: on-failure

  # tcp-exporter:
  #   build: 
  #     context: ../Metrics
  #     dockerfile: tcp.Dockerfile
  #   container_name: tcp-exporter
  #   network_mode: "host"
  #   restart: always
  #   volumes:
  #     - ../config.yml:/etc/tcp_exporter/tcp.yml
  #   ports:
  #     - 9191:9191
