version: '3.8'

services:

  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ../SNMPExporter/src/github.com/prometheus/snmp_exporter/generator/snmp.yml:/etc/snmp_exporter/snmp.yml
    network_mode: "host"
    # command: 
    #   - '--config.file=/etc/snmp_exporter/snmp.yml'
    restart: always
    ports:
      - 9116:9116
      - 116:116/udp
    # networks:
    #   - site-net
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #   placement:
    #     constraints:
    #       - node.role == worker

# sudo docker run -d --name snmp-exporter -p 9116:9116     -v ../SNMPExporter/src/github.com/prometheus/snmp_exporter/generator/snmp.yml:/etc/snmp_exporter/snmp.yml prom/snmp-exporter