version: '3.8'

# networks:
#   site-net:
#     attachable: true

services:

  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ../SNMPExporter/src/github.com/prometheus/snmp_exporter/generator/snmp.yml:/etc/snmp_exporter/snmp.yml
    network_mode: "host"
    ports:
      - 9116:9116
  
    # docker network create --driver=overlay --subnet=172.25.0.0/25 --gateway=172.25.0.1 --attachable=true test1
    # docker network create --driver=overlay --subnet=172.17.0.0/16 --gateway=172.17.0.1 --attachable=true --aux-address="my-switch=172.16.1.1" site3


    # command: 
    #   - '--config.file=/etc/snmp_exporter/snmp.yml'
    
    # networks:
    #   - site-net
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #   placement:
    #     constraints:
    #       - node.role == worker

# sudo docker run -d --name snmp-exporter -p 9116:9116     -v ../SNMPExporter/src/github.com/prometheus/snmp_exporter/generator/snmp.yml:/etc/snmp_exporter/snmp.yml prom/snmp-exporter