version: '3.8'

services:

  tcp-exporter:
    build: 
      context: ../Metrics
      dockerfile: tcp.Dockerfile
    container_name: tcp-exporter
    network_mode: "host"
    restart: always
    volumes:
      - ../config.yml:/etc/tcp_exporter/tcp.yml
    ports:
      - 9192:9192
