version: '3.8'

services:

  tcp-exporter:
    image: tcp_exporter
    network_mode: "host"
    restart: always
    volumes:
      - ../config.yml:/etc/tcp_exporter/tcp.yml
    ports:
      - 9192:9192
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
