version: '3'
services:
# NGINX service
  nginx:
    # NGINX uses the latest image
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    # NGINX service restart policy set to "always"
    # restart: always
    # Persist and share NGINX configuration data 
    volumes:
      - ./conf/:/etc/nginx/conf.d/
      - /etc/grafana/:/etc/nginx/ssl/
      - /etc/grafana/fullchain.pem:/etc/grafana/fullchain.pem
      - /etc/grafana/privkey.pem:/etc/grafana/privkey.pem
